### PR TITLE
Add visibility option

### PR DESCRIPTION
**Pull request by a21ns1g4ts**
This pull request adds the visibility option to the item, according to a pattern found in some packages like https://github.com/pxlrbt/filament-environment-indicator/blob/main/src/FilamentEnvironmentIndicator.php
https://github.com/bezhanSalleh/filament-shield

### CODE REVIEW

**Comment by Keysaw** [comment]
Thanks for the PR!

I tweaked it a little bit to use Laravel default authorization method, which should work well with Spatie Laravel Permission package.

This gives more flexibility to the users, while still allowing Super Admins to bypass these permissions.

**Comment by a21ns1g4ts** [comment]
HI. thanks. Are you can add and key to roles too ?

**Comment by Keysaw** [comment]
I added a role key in the config file, so you can define the visibility by role as well as permissions.

Check out the latest [1.1.1](https://github.com/Keysaw/laravel-filament-maintenance/releases/tag/1.1.1) version.

**Comment by a21ns1g4ts** [comment]
Very good my friend.. Nice work.

**Pull request merged**
